#!/bin/sh
# postrm script for vitexsoftware-website

set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
        . /usr/share/apache2/apache2-maintscript-helper
        apache2_invoke disconf vitexsoftware.cz
    fi
    
    if [ -f /etc/init.d/apache2 ] ; then
        if [ -x /usr/sbin/invoke-rc.d ]; then
            invoke-rc.d apache2 reload 3>/dev/null || true
        else
            /etc/init.d/apache2 reload 3>/dev/null || true
        fi
    fi
fi

#DEBHELPER#

exit 0
